"""Unsloth fine-tuning for Wanderly AI Travel Assistant.

Uses Unsloth + QLoRA for 2x faster training and 80% less VRAM vs vanilla QLoRA.
Works on Kaggle T4 (16 GB) and A100 (40 GB).

Input files (generated by convert_sft_v2_to_dashboard_payload.py):
    backend_fine_tuning/fine_tuning/data/processed/train.jsonl        (NO stored system prompt)
    backend_fine_tuning/fine_tuning/data/processed/validation.jsonl  (NO stored system prompt)

System prompt is injected at training time — not stored in the dataset files.
This keeps the dataset clean and avoids duplicating the system prompt.

Usage:
    # On Kaggle — add to top of notebook cell:
    import os
    os.environ["BASE_MODEL"]   = "meta-llama/Llama-3.2-3B-Instruct"
    os.environ["TRAIN_PATH"]   = "/kaggle/input/wanderly-sft-v2/train.jsonl"
    os.environ["VAL_PATH"]     = "/kaggle/input/wanderly-sft-v2/validation.jsonl"
    os.environ["OUTPUT_DIR"]   = "/kaggle/working/wanderly-3b-lora"
    os.environ["HF_API_TOKEN"] = "hf_xxx"

    # Smoke test (50 rows only — verify everything works before full run):
    SMOKE_TEST=1 python train_unsloth.py

    # Full training:
    python train_unsloth.py

    # 8B model (needs A100 or 2x T4):
    BASE_MODEL=meta-llama/Llama-3.1-8B-Instruct SEQ_LEN=4096 python train_unsloth.py
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

# ── Configuration ─────────────────────────────────────────────────────────────
BASE_MODEL = os.getenv("BASE_MODEL", "meta-llama/Llama-3.2-3B-Instruct")
HF_TOKEN   = os.getenv("HF_API_TOKEN") or os.getenv("HF_TOKEN") or os.getenv("HUGGING_FACE_HUB_TOKEN")

_ft_dir     = Path(__file__).resolve().parent.parent
_proc_dir   = _ft_dir / "data" / "processed"

TRAIN_PATH  = Path(os.getenv("TRAIN_PATH",  str(_proc_dir / "train.jsonl")))
VAL_PATH    = Path(os.getenv("VAL_PATH",    str(_proc_dir / "validation.jsonl")))

_slug       = BASE_MODEL.split("/")[-1].lower().replace(".", "").replace("-", "_")
OUTPUT_DIR  = Path(os.getenv("OUTPUT_DIR",  str(_ft_dir / "outputs" / f"{_slug}_unsloth_lora")))

# Hyper-parameters (override via env)
MAX_SEQ_LEN = int(os.getenv("SEQ_LEN",     "4096"))
LORA_R      = int(os.getenv("LORA_R",      "16"))
LORA_ALPHA  = int(os.getenv("LORA_ALPHA",  "32"))
EPOCHS      = int(os.getenv("EPOCHS",      "2"))
BATCH_SIZE  = int(os.getenv("BATCH",       "1"))
GRAD_ACCUM  = int(os.getenv("GRAD_ACC",    "8"))
LR          = float(os.getenv("LR",        "2e-4"))
SMOKE_TEST  = os.getenv("SMOKE_TEST", "0") == "1"   # train on 50 rows only
HF_CHECKPOINT_REPO_ID   = os.getenv("HF_CHECKPOINT_REPO_ID", "").strip()
HF_CHECKPOINT_REPO_TYPE = os.getenv("HF_CHECKPOINT_REPO_TYPE", "dataset").strip() or "dataset"
HF_CHECKPOINT_PREFIX    = os.getenv("HF_CHECKPOINT_PREFIX", "wanderly-3b-lora").strip() or "wanderly-3b-lora"

# ── System prompt (injected at training time — NOT stored in dataset files) ───
SYSTEM_PROMPT = (
    "You are Wanderly, an AI travel assistant for a dashboard web app. "
    "You will receive a user travel request, an API_CONTEXT block with live data "
    "(flights, hotels, weather, events), and optionally a DESTINATION_CONTEXT block "
    "with city-specific knowledge (attractions, foods, transport, costs). "
    "Rules: "
    "(1) Use ONLY data from API_CONTEXT and DESTINATION_CONTEXT — never invent flights, "
    "hotels, prices, availability, or events. "
    "(2) If DESTINATION_CONTEXT is missing, set intent to 'missing_destination_context', "
    "leave itinerary and map_data empty, and add 'destination_context' to api_grounding.missing_api. "
    "(3) If a live API field is missing, mark it in api_grounding.missing_api — do not invent data. "
    "(4) Return ONLY a valid JSON object — no markdown, no prose outside JSON. "
    "(5) dashboard_payload.schema_version must always be 'travel_dashboard_v1'."
)


def main() -> None:
    # ── 0. Check dependencies ─────────────────────────────────────────────────
    try:
        from unsloth import FastLanguageModel
        from unsloth import is_bfloat16_supported
        from trl import SFTTrainer, SFTConfig
        from datasets import load_dataset
        from transformers import TrainerCallback
        import torch
    except ImportError as e:
        print(f"[ERROR] Missing dependency: {e}")
        print("Install with:")
        print("  pip install unsloth")
        sys.exit(1)

    # ── 1. Validate inputs ────────────────────────────────────────────────────
    for path, name in [(TRAIN_PATH, "TRAIN_PATH"), (VAL_PATH, "VAL_PATH")]:
        if not path.exists():
            print(f"[ERROR] {name} not found: {path}")
            print("Run convert_sft_v2_to_dashboard_payload.py first.")
            sys.exit(1)

    print("=" * 60)
    print("Wanderly — Unsloth Fine-tuning")
    print("=" * 60)
    print(f"Base model  : {BASE_MODEL}")
    print(f"Train file  : {TRAIN_PATH}")
    print(f"Val file    : {VAL_PATH}")
    print(f"Output dir  : {OUTPUT_DIR}")
    print(f"MAX_SEQ_LEN : {MAX_SEQ_LEN}")
    print(f"LoRA        : r={LORA_R}, alpha={LORA_ALPHA}")
    print(f"Training    : {EPOCHS} epochs, batch={BATCH_SIZE}, grad_acc={GRAD_ACCUM}, lr={LR}")
    print(f"Smoke test  : {'YES (50 rows only)' if SMOKE_TEST else 'NO (full training)'}")
    if HF_CHECKPOINT_REPO_ID:
        print(f"HF backup   : {HF_CHECKPOINT_REPO_TYPE}/{HF_CHECKPOINT_REPO_ID}/{HF_CHECKPOINT_PREFIX}/")
    print()

    # ── 2. Load model + tokenizer (Unsloth 4-bit) ────────────────────────────
    print("Loading model via Unsloth (4-bit QLoRA)...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name    = BASE_MODEL,
        max_seq_length= MAX_SEQ_LEN,
        dtype         = None,       # auto: bfloat16 on A100, float16 on T4
        load_in_4bit  = True,
        token         = HF_TOKEN,
    )

    # ── 3. Add LoRA adapter ───────────────────────────────────────────────────
    print("Adding LoRA adapter (Unsloth optimised)...")
    model = FastLanguageModel.get_peft_model(
        model,
        r              = LORA_R,
        target_modules = [
            "q_proj", "k_proj", "v_proj", "o_proj",
            "gate_proj", "up_proj", "down_proj",
        ],
        lora_alpha     = LORA_ALPHA,
        lora_dropout   = 0,
        bias           = "none",
        use_gradient_checkpointing = "unsloth",  # Unsloth's memory-efficient checkpointing
        random_state   = 42,
        use_rslora     = False,
        loftq_config   = None,
    )
    model.print_trainable_parameters()

    # ── 4. Load dataset ───────────────────────────────────────────────────────
    print("\nLoading dataset...")
    train_ds = load_dataset("json", data_files=str(TRAIN_PATH), split="train")
    val_ds   = load_dataset("json", data_files=str(VAL_PATH),   split="train")

    if SMOKE_TEST:
        train_ds = train_ds.select(range(min(50, len(train_ds))))
        val_ds   = val_ds.select(range(min(10, len(val_ds))))
        print(f"  [SMOKE TEST] Using {len(train_ds)} train + {len(val_ds)} val rows")
    else:
        print(f"  {len(train_ds):,} train  |  {len(val_ds):,} validation rows")

    # ── 5. Format function (injects system prompt, applies chat template) ─────
    def format_with_system(example: dict) -> dict:
        """
        Prepend the system prompt to the stored user/assistant messages.
        The dataset files do NOT contain a stored system message — we inject here.
        """
        messages = [{"role": "system", "content": SYSTEM_PROMPT}] + example["messages"]
        text = tokenizer.apply_chat_template(
            messages,
            tokenize              = False,
            add_generation_prompt = False,
        )
        return {"text": text}

    print("Applying chat template + injecting system prompt...")
    train_ds = train_ds.map(format_with_system, num_proc=1)
    val_ds   = val_ds.map(format_with_system,   num_proc=1)

    # ── 6. Token length check (fail fast if dataset is too long) ─────────────
    print("Checking token lengths...")
    sample_texts  = train_ds["text"][:200]
    token_lengths = [len(tokenizer.encode(t)) for t in sample_texts]
    mean_len = sum(token_lengths) // len(token_lengths)
    max_len  = max(token_lengths)
    over_limit = sum(1 for l in token_lengths if l > MAX_SEQ_LEN)
    print(f"  Sample (first 200): mean={mean_len} tokens, max={max_len} tokens")
    print(f"  Over MAX_SEQ_LEN ({MAX_SEQ_LEN}): {over_limit}/{len(token_lengths)} rows")

    if over_limit > len(token_lengths) * 0.10:
        print(
            f"\n[WARNING] {over_limit/len(token_lengths)*100:.0f}% of sampled rows exceed MAX_SEQ_LEN={MAX_SEQ_LEN}.\n"
            "These rows will be truncated mid-JSON and produce broken outputs.\n"
            "Recommended: increase SEQ_LEN or run the trimmer in the converter script.\n"
        )

    # ── 7. Filter rows that exceed MAX_SEQ_LEN ────────────────────────────────
    print("Filtering rows exceeding MAX_SEQ_LEN...")

    def add_len(example: dict) -> dict:
        return {"token_len": len(tokenizer.encode(example["text"], add_special_tokens=False))}

    train_ds = train_ds.map(add_len, num_proc=1)
    val_ds   = val_ds.map(add_len,   num_proc=1)

    n_train_before = len(train_ds)
    n_val_before   = len(val_ds)
    train_ds = train_ds.filter(lambda x: x["token_len"] <= MAX_SEQ_LEN)
    val_ds   = val_ds.filter(lambda x:   x["token_len"] <= MAX_SEQ_LEN)

    dropped_train = n_train_before - len(train_ds)
    dropped_val   = n_val_before   - len(val_ds)
    if dropped_train or dropped_val:
        print(f"  Dropped: {dropped_train} train + {dropped_val} val rows (exceed {MAX_SEQ_LEN} tokens)")
    else:
        print(f"  All rows fit within {MAX_SEQ_LEN} tokens.")

    train_ds = train_ds.remove_columns(["token_len"])
    val_ds   = val_ds.remove_columns(["token_len"])
    print(f"  Final: {len(train_ds):,} train  |  {len(val_ds):,} validation\n")

    if len(train_ds) == 0:
        raise SystemExit(
            "[ERROR] No training rows remain after filtering.\n"
            f"All rows exceed SEQ_LEN={MAX_SEQ_LEN}. Increase SEQ_LEN or shorten rows."
        )

    # ── 8. Training ───────────────────────────────────────────────────────────
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    use_bf16 = is_bfloat16_supported()

    callbacks = []
    if HF_CHECKPOINT_REPO_ID:
        class HFCheckpointBackupCallback(TrainerCallback):
            def __init__(self, repo_id: str, repo_type: str, path_prefix: str):
                from huggingface_hub import HfApi
                self.api = HfApi(token=HF_TOKEN)
                self.repo_id = repo_id
                self.repo_type = repo_type
                self.path_prefix = path_prefix.strip("/")
                self.uploaded: set[str] = set()
                self.api.create_repo(
                    repo_id=repo_id,
                    repo_type=repo_type,
                    private=True,
                    exist_ok=True,
                )

            def on_save(self, args, state, control, **kwargs):
                step = state.global_step
                checkpoint_dir = Path(args.output_dir) / f"checkpoint-{step}"
                if not checkpoint_dir.exists():
                    print(f"[HF BACKUP] Checkpoint not found yet: {checkpoint_dir}")
                    return control
                key = str(checkpoint_dir.resolve())
                if key in self.uploaded:
                    return control
                path_in_repo = f"{self.path_prefix}/checkpoint-{step}"
                print(f"[HF BACKUP] Uploading {checkpoint_dir} -> {self.repo_type}/{self.repo_id}/{path_in_repo}")
                self.api.upload_folder(
                    repo_id=self.repo_id,
                    repo_type=self.repo_type,
                    folder_path=str(checkpoint_dir),
                    path_in_repo=path_in_repo,
                    commit_message=f"Add Wanderly checkpoint step {step}",
                )
                self.uploaded.add(key)
                print(f"[HF BACKUP] Done checkpoint-{step}")
                return control

        callbacks.append(
            HFCheckpointBackupCallback(
                repo_id=HF_CHECKPOINT_REPO_ID,
                repo_type=HF_CHECKPOINT_REPO_TYPE,
                path_prefix=HF_CHECKPOINT_PREFIX,
            )
        )

    sft_config = SFTConfig(
        output_dir                = str(OUTPUT_DIR),
        num_train_epochs          = 1 if SMOKE_TEST else EPOCHS,
        per_device_train_batch_size = BATCH_SIZE,
        per_device_eval_batch_size  = 1,
        gradient_accumulation_steps = GRAD_ACCUM,
        gradient_checkpointing    = True,
        learning_rate             = LR,
        bf16                      = use_bf16,
        fp16                      = not use_bf16,
        logging_steps             = 10,
        eval_strategy             = "epoch",
        save_strategy             = "epoch",
        save_total_limit          = 2,
        warmup_ratio              = 0.05,
        lr_scheduler_type         = "cosine",
        max_seq_length            = MAX_SEQ_LEN,
        dataset_text_field        = "text",
        report_to                 = "none",
        optim                     = "adamw_8bit",   # Unsloth recommends adamw_8bit
        packing                   = False,           # off — we already filtered lengths
    )

    trainer_kwargs = dict(
        model             = model,
        args              = sft_config,
        train_dataset     = train_ds,
        eval_dataset      = val_ds,
        callbacks         = callbacks,
        processing_class  = tokenizer,
    )
    try:
        trainer = SFTTrainer(**trainer_kwargs)
    except TypeError as exc:
        if "processing_class" not in str(exc):
            raise
        print("[WARN] This TRL version does not accept processing_class; falling back to tokenizer=tokenizer.")
        trainer_kwargs.pop("processing_class")
        trainer_kwargs["tokenizer"] = tokenizer
        trainer = SFTTrainer(**trainer_kwargs)

    print(f"{'[SMOKE TEST] ' if SMOKE_TEST else ''}Starting Unsloth QLoRA training...")
    print(f"  Effective batch size: {BATCH_SIZE * GRAD_ACCUM}")
    print(f"  Precision: {'bfloat16' if use_bf16 else 'float16'}")
    print()

    trainer.train()

    # ── 9. Save adapter ───────────────────────────────────────────────────────
    print("\nSaving LoRA adapter...")
    trainer.save_model(str(OUTPUT_DIR))
    tokenizer.save_pretrained(str(OUTPUT_DIR))
    print(f"[OK] Adapter saved -> {OUTPUT_DIR}")

    if SMOKE_TEST:
        print("\n[SMOKE TEST PASSED]")
        print("  Dataset loads correctly.")
        print("  System prompt injection works.")
        print("  Chat template applies correctly.")
        print("  Token length filter works.")
        print("  Training started and completed.")
        print("  Adapter saves correctly.")
        print()
        print("Run full training:")
        print("  python train_unsloth.py")
        return

    # ── 10. Quick generation test ─────────────────────────────────────────────
    print("\nRunning generation test...")
    FastLanguageModel.for_inference(model)

    test_messages = [
        {"role": "system",  "content": SYSTEM_PROMPT},
        {"role": "user",    "content": "Plan a 3-day trip from Stuttgart to Paris with EUR 700 budget."},
        {"role": "user",    "content": 'API_CONTEXT: {"flights": [{"airline": "EasyJet", "price": 175, "currency": "EUR", "departure_time": "08:30", "arrival_time": "10:15", "duration": "1h 45m"}], "hotels": [{"name": "Generator Paris", "area": "Canal Saint-Martin", "price_per_night": 32, "rating": 4.2, "currency": "EUR"}], "weather": {"summary": "Sunny, 22°C"}, "events": []}'},
    ]
    prompt_text = tokenizer.apply_chat_template(
        test_messages, tokenize=False, add_generation_prompt=True
    )
    inputs = tokenizer(prompt_text, return_tensors="pt").to(model.device)

    import torch
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens = 1024,
            do_sample      = False,
            temperature    = None,
            top_p          = None,
        )
    generated = tokenizer.decode(outputs[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True)
    print("\nGeneration test output (first 800 chars):")
    print(generated[:800])
    print("..." if len(generated) > 800 else "")

    # Validate JSON
    try:
        import json
        parsed = json.loads(generated.strip())
        if "assistant_message" in parsed and "dashboard_payload" in parsed:
            dp = parsed["dashboard_payload"]
            sv = dp.get("schema_version", "missing")
            print(f"\n[OK] Valid JSON output — schema_version: {sv}")
        else:
            print("\n[!] JSON valid but missing required keys")
    except json.JSONDecodeError:
        print("\n[!] Output is not valid JSON — check training quality")

    # ── 11. Summary ───────────────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("Training complete!")
    print("=" * 60)
    print(f"  Adapter : {OUTPUT_DIR}")
    print()
    print("Next steps:")
    print("  1. Merge and push to HF Hub:")
    print("     python backend_fine_tuning/fine_tuning/scripts/merge_and_push.py")
    print()
    print("  2. Update backend_fine_tuning/.env:")
    print("     HF_FINETUNED_MODEL=Naman-1718/wanderly-travel-3b")
    print()
    print("Inference settings (add to backend llm_service):")
    print("  max_new_tokens = 2048   # JSON output needs space")
    print("  do_sample      = False")
    print("  temperature    = None   # greedy decode for JSON")


if __name__ == "__main__":
    main()
